### ISSUE TITLE
css3

### ISSUE THREAD

**Issue by leftrk** [GH1995/articles#65]
用标签选择器绘制图1-2所示的3个圆

![image](https://user-images.githubusercontent.com/11362493/82354299-39166500-9a33-11ea-9187-806ecbbec1f5.png)

```html
  <figure>
    <div></div>
    <div></div>
    <div></div>
  </figure>
```

```css
figure {
  display: flex;
  justify-content: space-between;

  width: 350px;
  padding: 20px;

  background-color: silver;
}

div {
  width: 100px;
  height: 100px;
  border: 1px solid black;
  border-radius: 50%;
}
```

**Comment by leftrk** [comment]
![image](https://user-images.githubusercontent.com/11362493/82356047-a5926380-9a35-11ea-8efa-76e104cbe0a5.png)

```html
    <figure class="tree">
      <div class="branch">
        <span class="leaf"></span>
        <span class="leaf"></span>
        <span class="leaf"></span>
      </div>
      <div class="branch">
        <span class="leaf"></span>
        <span class="leaf"></span>
      </div>
    </figure>
```

```css
.tree {
  display: flex;
  flex-direction: column;
  justify-content: space-around;

  width: 30px;
  height: 300px;
  border-radius: 5px;

  background-color: saddlebrown;
}

.tree .branch {
  display: flex;
  justify-content: flex-end;

  width: 160px;
  height: 20px;
  border-radius: 10px;
  transform: rotate(-30deg);

  background-color: peru;
}

.tree .branch .leaf {
  width: 40px;
  height: 40px;
  border-radius: 100% 0 100% 0;
  transform: translateY(-100%);

  background-color: green;
}
```

**Comment by leftrk** [comment]
![image](https://user-images.githubusercontent.com/11362493/82358182-bd1f1b80-9a38-11ea-84be-517ebefcb1c6.png)
```html


    <figure class="triangle">
      <div><span></span></div>
      <div><span></span><span></span></div>
      <div>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
      <div>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
        <span></span>
      </div>
    </figure>
```

```less
.triangle {
    display: flex;
    flex-direction: column;
    align-items: center;

    width: 500px;

    div {
        display: flex;
        justify-content: space-between;

        height: 50px;
        margin: 5px;

        span {
            width: 50px;
            height: 50px;
            margin: 10px;
            border-radius: 50%;

            background-color: lightgreen;

            &:first-child, &:last-child {
                background-color: lightcoral;
            }
        }
    }
}
```
